from prototype.constants import DEFAULT_LETTER_HEIGHT, DEFAULT_LETTER_WIDTH
from sdl2 import SDL_Rect


def _clip_from_indices(x, y):
    return SDL_Rect(
        x * DEFAULT_LETTER_WIDTH,
        y * DEFAULT_LETTER_HEIGHT,
        DEFAULT_LETTER_WIDTH,
        DEFAULT_LETTER_HEIGHT)


_clips = {
    ' ': _clip_from_indices(0, 0),
    'a': _clip_from_indices(1, 0),
    'b': _clip_from_indices(2, 0),
    'c': _clip_from_indices(3, 0),
    'd': _clip_from_indices(4, 0),
    'e': _clip_from_indices(5, 0),
    'f': _clip_from_indices(6, 0),
    'g': _clip_from_indices(7, 0),
    'h': _clip_from_indices(8, 0),
    'i': _clip_from_indices(9, 0),
    'j': _clip_from_indices(10, 0),
    'k': _clip_from_indices(11, 0),
    'l': _clip_from_indices(12, 0),
    'm': _clip_from_indices(13, 0),
    'n': _clip_from_indices(14, 0),
    'o': _clip_from_indices(15, 0),
    'p': _clip_from_indices(16, 0),
    'q': _clip_from_indices(17, 0),
    'r': _clip_from_indices(18, 0),
    's': _clip_from_indices(19, 0),
    't': _clip_from_indices(0, 1),
    'u': _clip_from_indices(1, 1),
    'v': _clip_from_indices(2, 1),
    'w': _clip_from_indices(3, 1),
    'x': _clip_from_indices(4, 1),
    'y': _clip_from_indices(5, 1),
    'z': _clip_from_indices(6, 1),
    'A': _clip_from_indices(7, 1),
    'B': _clip_from_indices(8, 1),
    'C': _clip_from_indices(9, 1),
    'D': _clip_from_indices(10, 1),
    'E': _clip_from_indices(11, 1),
    'F': _clip_from_indices(12, 1),
    'G': _clip_from_indices(13, 1),
    'H': _clip_from_indices(14, 1),
    'I': _clip_from_indices(15, 1),
    'J': _clip_from_indices(16, 1),
    'K': _clip_from_indices(17, 1),
    'L': _clip_from_indices(18, 1),
    'M': _clip_from_indices(19, 1),
    'N': _clip_from_indices(0, 2),
    'O': _clip_from_indices(1, 2),
    'P': _clip_from_indices(2, 2),
    'Q': _clip_from_indices(3, 2),
    'R': _clip_from_indices(4, 2),
    'S': _clip_from_indices(5, 2),
    'T': _clip_from_indices(6, 2),
    'U': _clip_from_indices(7, 2),
    'V': _clip_from_indices(8, 2),
    'W': _clip_from_indices(9, 2),
    'X': _clip_from_indices(10, 2),
    'Y': _clip_from_indices(11, 2),
    'Z': _clip_from_indices(12, 2),
    '1': _clip_from_indices(13, 2),
    '2': _clip_from_indices(14, 2),
    '3': _clip_from_indices(15, 2),
    '4': _clip_from_indices(16, 2),
    '5': _clip_from_indices(17, 2),
    '6': _clip_from_indices(18, 2),
    '7': _clip_from_indices(19, 2),
    '8': _clip_from_indices(0, 3),
    '9': _clip_from_indices(1, 3),
    '0': _clip_from_indices(2, 3),
    ',': _clip_from_indices(3, 3),
    '.': _clip_from_indices(4, 3),
    ':': _clip_from_indices(5, 3),
    ';': _clip_from_indices(6, 3),
    '\'': _clip_from_indices(7, 3),
    '"': _clip_from_indices(8, 3),
    '!': _clip_from_indices(9, 3),
    '?': _clip_from_indices(10, 3),
    '@': _clip_from_indices(11, 3),
    '~': _clip_from_indices(12, 3),
    '#': _clip_from_indices(13, 3),
    '$': _clip_from_indices(14, 3),
    '%': _clip_from_indices(15, 3),
    '^': _clip_from_indices(16, 3),
    '&': _clip_from_indices(17, 3),
    '*': _clip_from_indices(18, 3),
    '(': _clip_from_indices(19, 3),
    ')': _clip_from_indices(0, 4),
    '-': _clip_from_indices(1, 4),
    '_': _clip_from_indices(2, 4),
    '=': _clip_from_indices(3, 4),
    '+': _clip_from_indices(4, 4),
    '[': _clip_from_indices(5, 4),
    '{': _clip_from_indices(6, 4),
    '}' : _clip_from_indices(7, 4),
    ']': _clip_from_indices(8, 4),
    '\\': _clip_from_indices(9, 4),
    '|': _clip_from_indices(10, 4),
    '<': _clip_from_indices(11, 4),
    '>': _clip_from_indices(12, 4),
    '/': _clip_from_indices(13, 4),
    'ä': _clip_from_indices(14, 4),
    'ö': _clip_from_indices(15, 4),
    'ü': _clip_from_indices(16, 4),
    'ß': _clip_from_indices(17, 4),
    'Ä': _clip_from_indices(18, 4),
    'Ö': _clip_from_indices(19, 4),
    'Ü': _clip_from_indices(0, 5),
    '°': _clip_from_indices(1, 5),
    '↑': _clip_from_indices(2, 5),
    '↓': _clip_from_indices(3, 5),
}


def get_clip(c):
    return _clips[c]
